name: Build uOFW
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build project
        run: |
          make -k
        uses: pspdev/pspdev@latest
      - name: Build documentation
        run: |
          mkdir github-pages
          cd github-pages
          doxygen ../docs/Doxyfile
      - name: Deploy documentation
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: github-pages
          CLEAN: true
